[package]
name = "advent-of-code-2020"
version = "0.1.0"
authors = ["Max Davidson <davidsonmax@gmail.com>"]
edition = "2021"
license = "MIT"

[dependencies]
itertools = "0.10.5"
lazy_static = "1.4.0"
pcre2 = "0.2.3"
regex = "1.7.0"
