name: CI

on: [push]

env:
  CI: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'

      - uses: actions/checkout@v2

      - name: Set up NPM cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-cache-v0-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-cache-v0-

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test -- --verbose --max-workers=2
